### ISSUE TITLE
Error during sgRNA design for CRISPR activation

### ISSUE THREAD

**Issue by fabtouzot** [crisprVerse/Tutorials#6]
Hi, I encounter an error at the very last step during the design of sgRNA for CRISPR activation.
Everything is going fine until I try to add the CRISPRai scores.

After typing the command line in R
 ```
results <- addCrispraiScores(gs,
                             gr=target_region,
                             tssObject=tss_human,
                             geneCol="gene_id",
                             modality="CRISPRa",
                             fastaFile=fastaPath,
                             chromatinFiles=chromatinFiles)

```
I get the following error message:

```
snapshotDate(): 2023-10-24
see ?crisprScoreData and browseVignettes('crisprScoreData') for documentation
loading from cache
/bin/sh: RNAfold: command not found
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/crisprScore/python/crisprai/getWeissmanScores.py", line 105, in <module>
    scores = predictWeissmanScore(tssTable, p1p2Table, sgrnaTable, libraryTable, pickleFile, fastaFile, chromatinFiles, modality, verbose)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/crisprScore/python/crisprai/getWeissmanScores.py", line 26, in predictWeissmanScore
    paramTable = getParamTable(tssTable, p1p2Table, sgrnaTable, libraryTable, fastaFile, chromatinFiles, verbose)
  File "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/crisprScore/python/crisprai/getWeissmanScores.py", line 61, in getParamTable
    raise Exception('Error generating parameter table.')
Exception: Error generating parameter table.
Erreur dans file(file, "rt") : impossible d'ouvrir la connexion
De plus : Message d'avis :
Dans file(file, "rt") :
  impossible d'ouvrir le fichier '/var/folders/64/0s_gdgs13436hlvh44zjw1q00000gn/T//RtmpMYYf2X/scores.txt' : No such file or directory
```

Here are my session info 

 ```
sessionInfo()
R version 4.3.3 beta (2024-02-20 r85965)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.6.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] fr_CA.UTF-8/fr_CA.UTF-8/fr_CA.UTF-8/C/fr_CA.UTF-8/fr_CA.UTF-8

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] crisprScoreData_1.6.0             ExperimentHub_2.10.0              AnnotationHub_3.10.0              BiocFileCache_2.10.1             
 [5] dbplyr_2.4.0                      BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.70.2                   rtracklayer_1.62.0               
 [9] BiocIO_1.12.0                     Biostrings_2.70.2                 XVector_0.42.0                    GenomicRanges_1.54.1             
[13] GenomeInfoDb_1.38.6               IRanges_2.36.0                    S4Vectors_0.40.2                  BiocGenerics_0.48.1              
[17] crisprDesignData_0.99.28          crisprDesign_1.4.0                crisprBase_1.6.0                 

loaded via a namespace (and not attached):
 [1] DBI_1.2.2                     bitops_1.0-7                  biomaRt_2.58.2                rlang_1.1.3                  
 [5] magrittr_2.0.3                Rbowtie_1.42.0                matrixStats_1.2.0             compiler_4.3.3               
 [9] RSQLite_2.3.5                 GenomicFeatures_1.54.3        dir.expiry_1.10.0             png_0.1-8                    
[13] vctrs_0.6.5                   stringr_1.5.1                 pkgconfig_2.0.3               crayon_1.5.2                 
[17] fastmap_1.1.1                 ellipsis_0.3.2                utf8_1.2.4                    Rsamtools_2.18.0             
[21] promises_1.2.1                tzdb_0.4.0                    purrr_1.0.2                   bit_4.0.5                    
[25] randomForest_4.7-1.1          zlibbioc_1.48.0               cachem_1.0.8                  jsonlite_1.8.8               
[29] progress_1.2.3                blob_1.2.4                    later_1.3.2                   DelayedArray_0.28.0          
[33] BiocParallel_1.36.0           interactiveDisplayBase_1.40.0 parallel_4.3.3                prettyunits_1.2.0            
[37] R6_2.5.1                      VariantAnnotation_1.48.1      stringi_1.8.3                 reticulate_1.35.0            
[41] Rcpp_1.0.12                   SummarizedExperiment_1.32.0   readr_2.1.5                   httpuv_1.6.14                
[45] Matrix_1.6-5                  tidyselect_1.2.0              abind_1.4-5                   yaml_2.3.8                   
[49] codetools_0.2-19              curl_5.2.0                    lattice_0.22-5                tibble_3.2.1                 
[53] withr_3.0.0                   Biobase_2.62.0                shiny_1.8.0                   basilisk.utils_1.14.1        
[57] KEGGREST_1.42.0               xml2_1.3.6                    pillar_1.9.0                  BiocManager_1.30.22          
[61] filelock_1.0.3                MatrixGenerics_1.14.0         crisprScore_1.6.0             generics_0.1.3               
[65] vroom_1.6.5                   RCurl_1.98-1.14               BiocVersion_3.18.1            hms_1.1.3                    
[69] xtable_1.8-4                  glue_1.7.0                    tools_4.3.3                   crisprBwa_1.6.0              
[73] GenomicAlignments_1.38.2      XML_3.99-0.16.1               grid_4.3.3                    AnnotationDbi_1.64.1         
[77] GenomeInfoDbData_1.2.11       basilisk_1.14.3               restfulr_0.0.15               cli_3.6.2                    
[81] rappdirs_0.3.3                fansi_1.0.6                   S4Arrays_1.2.0                dplyr_1.1.4                  
[85] Rbwa_1.6.0                    crisprBowtie_1.6.0            digest_0.6.34                 SparseArray_1.2.4            
[89] rjson_0.2.21                  memoise_2.0.1                 htmltools_0.5.7               lifecycle_1.0.4              
[93] httr_1.4.7                    mime_0.12                     bit64_4.0.5                  
> 
```
Could you help me on this matter ?
Best

**Comment by Jfortin1** [comment]
Hi @fabtouzot, it seems that the `RNAfold` command is not found -- can you try installing [ViennaRNA](https://www.tbi.univie.ac.at/RNA/) on your machine and see if this solves the problem?
